### ISSUE TITLE
Blank loadables interrupts to run investigate, even in "disabled" mode

### ISSUE THREAD

**Issue by Riddalmorning** [circleguard/circleguard#109]
![Screenshot_5](https://user-images.githubusercontent.com/75766843/101836172-52f5d180-3b56-11eb-877f-83f0548a9467.png)
I don't think it should work this way

**Comment by tybug** [comment]
good point, oversight on my part. Will change

**Comment by tybug** [comment]
fixed in next release (5f392c1f77d97c15d3147081890c3ba78362689a)
