### ISSUE TITLE
Suggestion: Screenshot of frametime histogram in template

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#116]
By now, the template output for timewarp includes only limited information on the frametime. As looking at the frametime histogram can be important to rule out a potential false-positive, users who review the report and need to be sure about whether the score in question was cheated or not will have to look at the frametime histograph itself. To make this easier for them, the option to include a screenshot in the template could be of use.
I suggest a potential ShareX-integration of some sort could be a well solution since many community members use it.

**Comment by tybug** [comment]
don't think this will ever happen. a lot of effort for little gain.
