### ISSUE TITLE
error when using circleguard:// url with no api key

### ISSUE THREAD

**Issue by livxy** [circleguard/circleguard#120]
Whenever I type in a link for Circleguard on Google, then hit Enter, I get an error from Circleguard saying:

Fatal error detected
"Failed to execute script main"
![image](https://user-images.githubusercontent.com/67598470/103448309-e1490900-4c65-11eb-9d61-e6f106e6f958.png)

**Comment by tybug** [comment]
This was due to an incorrect api key, resulting in an error when trying to download the replay off the circleguard:// link. We probably want to guard against this and provide a nicer error message while still opening circleguard instead of crashing.

**Comment by tybug** [comment]
I can't reproduce this anymore, and I'm not entirely sure why the application ever would have crashed instead of erroring (and printing to terminal). We could make the error message nicer but this happens so rarely that I don't think it's a big deal.
