### ISSUE TITLE
Circleguard sometimes not ignoring non-hitobject snaps?

### ISSUE THREAD

**Issue by Riddalmorning** [circleguard/circleguard#123]
![Screenshot_22](https://user-images.githubusercontent.com/75766843/105626854-c3755b00-5e43-11eb-92f9-a6fe98996dbd.png)
open in circleguard: circleguard://m=2769844&u=448316&m1=HDHR

and yes, my "ignoring non-hitobject snaps" option is enabled

**Comment by tybug** [comment]
in short this is happening because that frame actually is on a hitobject, just one many seconds in the past. I need to take the time value of a hitobj into account as well as its position. Should be a simple fix.

**Comment by myangelaku** [comment]
[osu!std] Coolio | Aim Correction

Profile: https://osu.ppy.sh/users/3566985

replay: https://osu.ppy.sh/scores/osu/2332456533

open in circleguard: circleguard://m=652927&u=3566985&m1=NM

Snaps according to https://github.com/circleguard/circleguard:

| Time (ms) | Angle (°) | Distance (px) |
| :-: | :-: | :-: |
| 80736 | 3.70 | 20.81 |


Here's another example

**Comment by tybug** [comment]
fixed in https://github.com/circleguard/circlecore/commit/56ae2007b5e296eeb683f0e94b83d71f0ca8472f
