### ISSUE TITLE
Auto adjusting circle size not working for EZ replays

### ISSUE THREAD

**Issue by Riddalmorning** [circleguard/circleguard#127]
![ezrep](https://user-images.githubusercontent.com/75766843/107097374-dd3c7800-681d-11eb-9dc2-e49339b4c6ae.gif)
When you visualize a EZ replay, circle size is not scaled for EZ, but for NM

**Comment by tybug** [comment]
closed in https://github.com/circleguard/circlevis/commit/34fc0dd2e7626807420588a11c3659e7c4bfea22
