### ISSUE TITLE
Treat duplicates as one play

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#136]
Context:
![](https://myangel.aku.lu/fov2GbwT.png)
(https://discord.com/channels/532476765860265984/539956865245904906/824046509103251476)
![](https://myangel.aku.lu/K2Q3F0GK.png)
(https://discord.com/channels/532476765860265984/539956865245904906/785199789218201600)

**Comment by tybug** [comment]
closed in 7ca029d9bb61454fbd144b4bfe1cdf41cada997d
