### ISSUE TITLE
Fake snap in visualizer

### ISSUE THREAD

**Issue by Riddalmorning** [circleguard/circleguard#142]
INFO box
![Screenshot_52](https://user-images.githubusercontent.com/75766843/113472950-0d477680-946f-11eb-9720-18049befcb9e.png)
Visualizer
![Screenshot_51](https://user-images.githubusercontent.com/75766843/113472957-159fb180-946f-11eb-9b0e-465956d4108e.png)
There is no yellow line
![Screenshot_53](https://user-images.githubusercontent.com/75766843/113472968-336d1680-946f-11eb-9b42-f77567ef0311.png)
Was checking bunch of loadables, but i think url would be enough
circleguard://m=221948&u=2704753&m1=HDHR
I think it's related with #134 , but in reverse. My thresholds lower than visualizer

**Comment by tybug** [comment]
You're correct, it's the same issue. Closed in 41dc1b99fdce5fd450a229e9f54d23d8ad518b40
