### ISSUE TITLE
Export as gif

### ISSUE THREAD

**Issue by tybug** [circleguard/circleguard#15]
Would be neat to export a result as a gif for easy sharing on reports or elsewhere. Unsure of how feasible this is when all the drawing/frames is handled by qt, but something to look into.

**Comment by InvisibleSymbol** [comment]
This is certainly something I plan to add. We discussed this in the discord server and came to the conclusion that a record button would be the best solution, since the full replay is too long and the gifs would be hard to navigate, since most sites don't have controls on gifs.

**Comment by tybug** [comment]
I'm going to close this as something that would be undeniably useful, but only marginally so. Existing recording options exist (OBS etc) and are not difficult to use. It is time consuming to record the entirety of a replay (on 1x speed) through OBS or an external application, but I don't think people do that often enough for us to accommodate it.

I also don't really know what I'm doing when it comes to recording videos. I / @Stedoss have something that works, but takes a long time and yields low quality gifs, much lower than what an external application would give you. I'm sure all kinds of optimizations exist but I just don't know enough to do so, nor do I think it's worth it.

If someone in the future wants to try implementing this, you're welcome to - but it should be at least as high quality and fast to render as a recording from an external application (or only slightly less so), otherwise I don't think it's worth adding.
