### ISSUE TITLE
Show judgments and UI elements in visualizer

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#150]
Specifically misses, 300s, 100s and 50s, also maybe a better keypress counter and a combo counter. Minimalistic style would be good, I don't think anyone wants an osu! client copycat

(Context: https://discord.com/channels/532476765860265984/532476765860265986/830621000114765855 / https://discord.com/channels/532476765860265984/532476765860265986/830624051759808522)

###### I'm really surprised there wasn't an issue for this yet

**Comment by tybug** [comment]
Going to close this as implemented recently in circlevis, but only the judgments and hit error bar portion. Keypress counter and combo counter can be tracked in additional issues since those are more complicated
