### ISSUE TITLE
API key link broken

### ISSUE THREAD

**Issue by bbzlazer** [circleguard/circleguard#155]
The link [https://old.ppy.sh/p/api](https://old.ppy.sh/p/api) is broken and should be replaced with [https://osu.ppy.sh/p/api](https://osu.ppy.sh/p/api)

**Comment by myangelaku** [comment]
How is it broken..?
!(https://cdn.discordapp.com/attachments/533402800390930435/835021624867815464/Screenshot_20210423-071735_Brave.jpg)

**Comment by tybug** [comment]
I don't think it actually matters (both links should go to the same place), but https://github.com/ppy/osu-api/wiki does link to new web instead of old web, so I'm not against switching to the new web link

**Comment by bbzlazer** [comment]
Weird. I swear the first time i tried it the link redirected to the forum.

**Comment by tybug** [comment]
That's a known bug (that won't be fixed, low priority for the osu! team) unfortunately: https://github.com/ppy/osu-web/issues/2867

**Comment by bbzlazer** [comment]
k thanks
