### ISSUE TITLE
Incredible lag when visualizing 100 plays at once

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#162]
https://youtu.be/gr9WZupNmng
(https://discord.com/channels/532476765860265984/532477317382144001/848623893820342292)

**Comment by tybug** [comment]
going to close this for now per the above pr. At the very least visualizing 100 replays should now have better performance than the 2fps shown in the video, but there may be more legitimate performance issues (eg only getting 30fps instead of 60) which would deserve their own issue.
