### ISSUE TITLE
Progression bar doesn't change status from "Ratelimited" to "Loading replays"

### ISSUE THREAD

**Issue by Riddalmorning** [circleguard/circleguard#176]
Let's say for example, you run a top 100 on map and you don't have a cached replays for it.
After first ratelimit, progression bar status will be changed from "Loading replays" to "Ratelimited". But.
Theoretically, after ratelimit time ends, progression bar status should be changed to "Loading replays" again, but it doesn't happends.
It stays "Ratelimited" until all replays are loaded, then continues as normal with "Investigating replays"

**Comment by myangelaku** [comment]
Oh wow, [I have this bug it as well](https://youtu.be/NhlqnjQeU3k). Nice find!

**Comment by tybug** [comment]
closed by 9499c0076af7e60de0de572fd2856b71d0f5dbda
