### ISSUE TITLE
Visualizer crashes on SYUNN - Abraxas 

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#177]
They can be investigated in any way, though. Circleguard freezes after trying to load it, then it's stuck in this window:
![dwm_XtMmQIk2x7](https://user-images.githubusercontent.com/28674643/147101244-2443177f-4333-46a8-a770-2b17654fe26f.png)

Map link: https://osu.ppy.sh/beatmapsets/886209#osu/1853289
Replays for testing: https://cdn.discordapp.com/attachments/539956865245904906/923203327473365042/NekoKamui_-_SYUNN_-_Abraxas_Another_AR9.5_2021-12-19_Osu-FAkx.osr.osr https://cdn.discordapp.com/attachments/539956865245904906/923206647764107324/MyAngelAku_-_SYUNN_-_Abraxas_Another_AR9.5_2021-12-22_Osu.osr

Context: https://discord.com/channels/532476765860265984/539956865245904906/923203327636934686

**Comment by tybug** [comment]
closed by https://github.com/circleguard/circlevis/commit/e3ea33aad3de53a58e064b926076c4afeaf86601
