### ISSUE TITLE
Use non-rectangular icon for macos

### ISSUE THREAD

**Issue by tybug** [circleguard/circleguard#18]
Rectangular icons are associated with system applications on osx. Our icon should be circular, or slightly tilted (see: textedit, typora, and xcode icons). I don't see the current icon looking very good under either of these scenarios, however.

**Comment by InvisibleSymbol** [comment]
![](https://i.fiery.me/mOD8.png)
This is my first attempt at such icon. If this looks fine it would most likely be an extra icon for mac; If we want a round icon for everything the current sharp letters design is not the best idea.

**Comment by tybug** [comment]
Bit of a copy of discord's icon (not that I'm complaining that much). Maybe a bit of a darker border than the inside blue would work, instead of going for a white?

**Comment by InvisibleSymbol** [comment]
A new Icon has been added for mac os, which will be used in the next release.
![](https://i.fiery.me/p0Yn.png)
