### ISSUE TITLE
add all four input keys to the visualiser (m1, m2, k1, k2)

### ISSUE THREAD

**Issue by hyyhsuzy** [circleguard/circleguard#180]
this could be useful for analysing replays of those who use keys other than k1 and k2, especially if both k1 and m1 are pressed, since they both show up the same way. (unless you open the replay logs from the results screen)

**Comment by tybug** [comment]
only concern is this will take up more space than before, but I do think it's best if we add all four keys to the visualizer.

**Comment by hyyhsuzy** [comment]
sounds good, find it hard to look at my own replays due to this, so it can mitigate this issue I've had as well.

**Comment by tybug** [comment]
closed by https://github.com/circleguard/circlevis/commit/c42d212ffdc6555d4140c69842c5e81e88d4a3ef

just so I can double check, do you mind uploading a replay with all the four different keys pressed in it?

**Comment by hyyhsuzy** [comment]
https://discord.com/channels/532476765860265984/532476765860265986/931925744874041464 here you go!

**Comment by tybug** [comment]
Thanks, looks good.
