### ISSUE TITLE
Relax replays frametime

### ISSUE THREAD

**Issue by Spiroww** [circleguard/circleguard#188]
Everytime when u load relax replay into circleguard it shows 2.0avg or even 0.7avg. People think that scores like this is cheated. Is it worth to check relax replays in circleguard? Or maybe 2.0avg or lower is fine for relax?

**Comment by myangelaku** [comment]
Just check the frametime histogram and see if there is a significant peak after the lower ones that isn't on 16 and no peak at 16, it's probably timewarp (check the Wiki for more information).
Frametime averages values aren't to be interpreted to be evidence on any Relax replays.

**Comment by Spiroww** [comment]
![image](https://user-images.githubusercontent.com/89928282/185032516-cc0b7969-3530-4814-9564-356b2ae1d7a6.png)
I need expert opinion, is that timewarped?

**Comment by myangelaku** [comment]
I **am** an expert. Read the Wiki :)
Also, the GitHub issues section is meant to serve actual issues with the program (e.g. crashes, feature requests), if you need assistance like this, and are really too lazy to read the documentation, at least ask in the Discord. 


(The histogram indicates that this is probably not timewarped, which doesn't exclude the possibility that it's still timewarped.)

**Comment by Spiroww** [comment]
Ok, thank you very much!!
