### ISSUE TITLE
Up map replay range to 1-1000

### ISSUE THREAD

**Issue by amnezziaa** [circleguard/circleguard#191]
This is more of a question than an issue to be honest. Is there any way the current map replay range for circleguard `(1-100)` could be upped to `(1-1000)` since replays are stored until **1k**. I am aware they might be restrictions based on the **API** and so on but what is truly causing this `100` limit and is there a way it could be improved in circleguard ?

As for the usage perspective, when scanning popular maps and looking for replay stealing we surely are missing on some plays since we can't look for more than 100th.

**Comment by myangelaku** [comment]
You can only view the top 100 leaderboard using apiv1. If you want to get replays above that range, you can still add mod leaderboards as loadables.

**Comment by tybug** [comment]
this is a hard limitation of the api, which limits map queries to top 100 (even though top 1000 are stored). As @myangelaku said you can do a little bit better by specifying mods first and a limit of 100, but there's no guarantee you'll ever be able to find all 1k replays on the map.

**Comment by amnezziaa** [comment]
I see, thank you for the explanation. I had no clue that the API limited the request to 100 scores but it makes sense. Will try to use mod leaderboards more !
