### ISSUE TITLE
Filtering by mods

### ISSUE THREAD

**Issue by Maaster** [circleguard/circleguard#28]
Would be good to filter for mods on the given map.
I.E. if the top10 of a map is 3mod and you are just looking for HDDT/HDNC, do not download the 3mod plays (or any 1mod play).
Also treat DT as equal to NC, iirc they have different markings in the API Response.

**Comment by Smitty1298** [comment]
Great idea, we already have talked about implementing this. Modded leader-board support will be worked on as well as a profile checker.
