### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by obrigadex** [circleguard/circleguard#51]
Imma be straight to the point, there you have some suggestions

_**Check Local:**_
- Option to choose a replay instead of choosing the complete folder.
- Choose mods that we want to compare.

_**Check Map:**_
- Choose mods that we want to compare.

_**Visualizer:**_ 
- Option to turn on or off circles and sliders (and reverse arrows) to the replay

_**New tabs:**_ 
- Replay analytics like firedigger's replay analyzer. i guess that it would be very cool xd

**_Others:_**
- Be able to make "Results" tab get to a new window, like debug output.
- Make the same thing with "Queue"
- Change background color
- Make Message Format on settings editable from .txt directly.

I dont know if theso suggestions are possible to make ;-;

**Comment by tybug** [comment]
> _**Check Local:**_
> 
> * Option to choose a replay instead of choosing the complete folder.
> * Choose mods that we want to compare.

Already addressed by #48 

> _**Check Map:**_
> 
> * Choose mods that we want to compare.

Addressed by #48 

> _**Visualizer:**_
> 
> * Option to turn on or off circles and sliders (and reverse arrows) to the replay

We don't visualize beatmaps at all right now, so I assume you're talking about in the future (see #41). Don't know how much we'll support turning on or off certain elements. Why would only seeing circles or only seeing sliders be useful?

> _**New tabs:**_
> 
> * Replay analytics like firedigger's replay analyzer. i guess that it would be very cool xd

Mmm that could be useful. Would be a circlecore addition if anything.

> **_Others:_**
> 
> * Be able to make "Results" tab get to a new window, like debug output.
> * Make the same thing with "Queue"

I understand the desire for this, but there are many combinations of "x window separate and others stay in the main window". Not too excited to implement this one ([feature creep](https://en.wikipedia.org/wiki/Feature_creep))

> * Change background color

Of the whole application? We can offer a setting that changes the qt stylesheet, but that's about it.

> * Make Message Format on settings editable from .txt directly.

Already merged to release branch (#38)

**Comment by tybug** [comment]
going to close as either implemented or tracked elsewhere
