### ISSUE TITLE
Scaling issues on windows

### ISSUE THREAD

**Issue by InvisibleSymbol** [circleguard/circleguard#54]
Setting the scaling on windows to anything above 100% results in a broken looking gui. The cause seems to be that the padding scales but the font doesn't.
![](https://i.fiery.me/MGs50.png)
Also the buttons in the visualizer appear to have no padding at all.
![](https://i.fiery.me/8PQzP.png)

**Comment by Cyuubi** [comment]
![image](https://user-images.githubusercontent.com/24927193/71751913-26680e80-2e4b-11ea-8dec-391b333cdce7.png)

**Comment by Cyuubi** [comment]
![image](https://user-images.githubusercontent.com/24927193/71751916-28ca6880-2e4b-11ea-8db9-fb3bacb00081.png)

**Comment by Cyuubi** [comment]
![image](https://user-images.githubusercontent.com/24927193/71751918-2c5def80-2e4b-11ea-822a-26a707335bca.png)

**Comment by Cyuubi** [comment]
![image](https://user-images.githubusercontent.com/24927193/71751921-2ec04980-2e4b-11ea-9f25-6a590e786e14.png)
