### ISSUE TITLE
Change visualizer icons

### ISSUE THREAD

**Issue by tybug** [circleguard/circleguard#55]
It's rather confusing to always see a pause icon on the visualizer, even when it's paused (one would expect to see a play icon then). I suggest we make the pause button change icons if the visualizer is paused, and change the frame advance and frame retreat icons to something like [this](https://cdn1.iconfinder.com/data/icons/media-player-icons-1/48/icon_next_frame-512.png), to avoid confusion with the play icon.

**Comment by InvisibleSymbol** [comment]
added by https://github.com/circleguard/circleguard/commit/99a1b1e57f5c6cc492d58f2cbd3df39ce38fea2f
