### ISSUE TITLE
Visualizer Improvments

### ISSUE THREAD

**Issue by InvisibleSymbol** [circleguard/circleguard#56]
ordered by importance
- [x] mods used next to users
- [x] keys pressed next to users (two squares)
- [x] should be able to show info of at least 50 users
- [x] info shouldn't intrude into visualization (make window wider)
- [x] option to disable rendering of the beatmap #51 
- [x] add that fancy frametime graph but without spaghetti code
- [ ] make `get_hitobjects` faster
- [ ] remove api dependency- if we don't have the ability, fall back to what we have. Also check map using hash instead of beatmap_id; the latter requires the api
- [ ] draw sliderball
- [ ] switch to drawing images of circles instead of circles
- [ ] Add Skin support
- [ ] draw nicer sliders

**Comment by tybug** [comment]
Should track this in https://github.com/circleguard/circleguard/projects/1 instead? Let me know if you disagree, or close when you've transferred things over to the project otherwise
